### ISSUE TITLE
Runtime error with legacy adapter main and node runner

### ISSUE THREAD

**Issue by Mayeu** [elm-community/elm-test#143]
Hello,

I am using travis to run my test and I get the following error (making the build fail) after the test:
```
$ $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-test
Running elm-make with sysconfcpus -n 2
Success! Compiled 2 modules.
Successfully generated /tmp/elm_test_117225-2526-lpdymz.js

TEST RUN PASSED

Passed: 46
Failed: 0

Exit code: 0
The test run failed because it encountered a runtime exception:

 [TypeError: testModule.worker is not a function]

The command "$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-test" exited with 2.
```

You can see the [.travis.yml used](https://github.com/Mayeu/elm-integer/blob/432dfb56eaf7e5d3812c28e328e121d892d89d3a/.travis.yml), and the [travis run](https://travis-ci.org/Mayeu/elm-integer/jobs/214950693).

I am also encountering this on my laptop (Mac OS X 10.11.6, elm 0.18, node 7.7.3):
```
$ elm-test
Success! Compiled 2 modules.
Successfully generated /var/folders/tj/1qfj1r9j61bfcpfdsl6m9dsm0000gn/T/elm_test_117225-73697-1wb0sde.13yc01wcdi.js

TEST RUN PASSED

Passed: 46
Failed: 0

Exit code: 0
(node:73697) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: testModule.worker is not a function
(node:73697) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any help would be appreciated :)

**Comment by rtfeldman** [comment]
What version of `node-test-runner` are you using?

**Comment by Mayeu** [comment]
Is it possible that I do not use any?

Both (travis + laptop) `tests/elm-stuff/exact-dependencies.json` look like this:
```
{
    "elm-community/lazy-list": "1.0.0",
    "elm-community/elm-check": "2.0.1",
    "elm-community/elm-test": "3.1.0",
    "elm-community/shrink": "2.0.0",
    "elm-lang/virtual-dom": "2.0.4",
    "elm-community/random-extra": "2.0.0",
    "mgold/elm-random-pcg": "4.0.2",
    "elm-lang/lazy": "2.0.0",
    "elm-lang/html": "2.0.0",
    "rtfeldman/legacy-elm-test": "3.0.0",
    "rtfeldman/html-test-runner": "2.0.0",
    "elm-lang/trampoline": "1.0.1",
    "elm-lang/core": "5.1.1"
}
```

For references, here is the `elm-packages.json`:
```
{
    "version": "2.0.2",
    "summary": "Infinite-size integers for Elm",
    "repository": "https://github.com/javcasas/elm-integer.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [
        "Data.Integer"
    ],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

and `tests/elm-packages.json`:
```
{
    "version": "0.0.1",
    "summary": "Infinite-size integers for Elm",
    "repository": "https://github.com/javcasas/elm-integer.git",
    "license": "BSD3",
    "source-directories": [
        "../src",
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-community/elm-check": "2.0.1 <= v < 3.0.0",
        "rtfeldman/legacy-elm-test": "3.0.0 <= v < 4.0.0",
        "elm-lang/core": "5.0.0 <= v < 6.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

**Comment by Mayeu** [comment]
Also, the [tests file](https://github.com/Mayeu/elm-integer/blob/432dfb56eaf7e5d3812c28e328e121d892d89d3a/tests/Main.elm) looks like that:

```elm
module Main exposing (..)

import Check exposing (quickCheck, Claim, claim, that, is, for)
import Check.Producer exposing (int, tuple, rangeInt)
import Data.Integer exposing (..)
import Legacy.Check.Test as CheckTest
import Legacy.ElmTest as ElmTest exposing (..)
import Maybe exposing (Maybe)


integer : Check.Producer.Producer Integer
integer =
    Check.Producer.map (\a -> fromInt a) int

[snip lot of test]

allTests : Test
allTests =
    suite "All tests"
        [ addTests
        , negateTests
        , subTests
        , mulTests
        , toStringTests
        , fromStringTests
        , minMaxTests
        , compareTests
        , divmodTests
        , max_digit_valueTests
        , CheckTest.evidenceToTest (quickCheck qcAdd)
        , CheckTest.evidenceToTest (quickCheck qcNegate)
        , CheckTest.evidenceToTest (quickCheck qcSub)
        , CheckTest.evidenceToTest (quickCheck qcMul)
        , CheckTest.evidenceToTest (quickCheck qcDivMod)
        , CheckTest.evidenceToTest (quickCheck qcAbs)
        , CheckTest.evidenceToTest (quickCheck qcSign)
        ]


main =
    ElmTest.runSuite allTests
```

**Comment by rtfeldman** [comment]
Sorry, I meant the binary - if you run `elm-test --version` what's the output?

**Comment by Mayeu** [comment]
On travis:
```
$ elm-test --version
0.18.2
```

On my laptop:
```
🍵 elm-test --version
0.17.3
```

I just updated elm-test on my laptop, but the error is still there:

```
🍵 elm-test --version
0.18.2

🍵 elm-test
Success! Compiled 1 module.
Successfully generated /var/folders/tj/1qfj1r9j61bfcpfdsl6m9dsm0000gn/T/elm_test_117225-89207-1b68hzn.foq32nvcxr.js

TEST RUN PASSED

Passed: 46
Failed: 0

Exit code: 0
The test run failed because it encountered a runtime exception:

 TypeError: testModule.worker is not a function
    at evalElmCode (/usr/local/lib/node_modules/elm-test/bin/elm-test:178:24)
    at /usr/local/lib/node_modules/elm-test/bin/elm-test:303:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Mayeu** [comment]
On travis:
```
$ elm-test --version
0.18.2
```

On my laptop:
```
🍵 elm-test --version
0.17.3
```

I just updated elm-test on my laptop, but the error is still there:

```
🍵 elm-test --version
0.18.2

🍵 elm-test
Success! Compiled 1 module.
Successfully generated /var/folders/tj/1qfj1r9j61bfcpfdsl6m9dsm0000gn/T/elm_test_117225-89207-1b68hzn.foq32nvcxr.js

TEST RUN PASSED

Passed: 46
Failed: 0

Exit code: 0
The test run failed because it encountered a runtime exception:

 TypeError: testModule.worker is not a function
    at evalElmCode (/usr/local/lib/node_modules/elm-test/bin/elm-test:178:24)
    at /usr/local/lib/node_modules/elm-test/bin/elm-test:303:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by mgold** [comment]
@Mayeu Can you please start removing tests from `allTests` until you can give us a minimal unsnipped source of what's causing the issue?

**Comment by Mayeu** [comment]
I'll try to do that :+1: (Not sure when, I am only doing elm on my spare time :) )

**Comment by Mayeu** [comment]
I don't think I can be more minimal than this:
```elm
module Main exposing (..)

import Legacy.ElmTest as ElmTest exposing (..)


allTests : Test
allTests =
    suite "All tests"
        [ equals 1 1 ]


main =
    ElmTest.runSuite allTests
```

:)

**Comment by Mayeu** [comment]
For your convenience I package the whole minimal project things into [a repository](https://github.com/Mayeu/elm-test-runtime-exception) with Travis CI configured.

**Comment by mgold** [comment]
Thanks! I'm able to reproduce the error with `elm test` as you report. If I `cd tests` and `elm-reactor`, it seems to run without the error. So it seems to be an issue with the node runner and the legacy `ElmTest`.

This lead me to the obvious-in-hindsight realization that you're using the legacy way of running the test itself. Changing that out for the new way fixed the issue. I'll post an issue on your repo with more info.

Although this fix allows you to keep using the legacy adapter, I can advise you that legacy support will be dropped in 0.19, which is likely a few months away. So you should think about changing over to the new library. Thankfully you can do it one test at a time!

**Comment by Mayeu** [comment]
Ha I see! Thank you for your feedback :)

I will ping the owner of the original repo about the legacy test situation and elm 0.19, the library I am trying to use is a little over my knowledge of arithmetic to fix that myself ^^

Closing this issue then.
