### ISSUE TITLE
Debug.Crash

### ISSUE THREAD

**Issue by splodingsocks** [elm-community/elm-test#16]
I ran a simple example test suite today with the latest version of elm-test, and Elm 0.17

`Example.elm`
```elm
module Example exposing (..)

import String
import ElmTest exposing (..)


tests : Test
tests =
    suite "A Test Suite"
        [ test "Addition" (assertEqual (3 + 7) 10)
        , test "String.left" (assertEqual "a" (String.left 1 "abcdefg"))
        , test "This test should fail" (assert False)
        ]


main : Program Never
main =
    runSuite tests

```

And then I ran:

`elm-make Example.elm --output example.js && node example.js`

And got the following output:
```
Success! Compiled 0 modules.
Successfully generated example.js
/Users/murphy/projects/kuali/elm-forms/test/example.js:501
                throw new Error(
                ^

Error: Ran into a `Debug.crash` in module `ElmTest.Runner.Console`

This was caused by the `case` expression between lines 28 and 33.
One of the branches ended with a crash and the following value got through:

    False

The message provided by the code author is:

      1 suites run, containing 3 tests
  0 suites and 2 tests passed
  1 suites and 1 tests failed

Test Suite: A Test Suite: FAILED
  Addition: passed.
  String.left: passed.
  This test should fail: FAILED. not True
    at /Users/murphy/projects/kuali/elm-forms/test/example.js:501:9
    at _elm_community$elm_test$ElmTest_Runner_Console$runDisplay (/Users/murphy/projects/kuali/elm-forms/test/example.js:7251:9)
    at _elm_community$elm_test$ElmTest_Runner_Console$runSuite (/Users/murphy/projects/kuali/elm-forms/test/example.js:7266:11)
    at Object.<anonymous> (/Users/murphy/projects/kuali/elm-forms/test/example.js:7363:8)
    at Object.<anonymous> (/Users/murphy/projects/kuali/elm-forms/test/example.js:7398:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

Another peep on Slack repro'd and referenced the following (or something close to it):
https://github.com/elm-community/elm-test/blob/master/src/ElmTest/Runner/Console.elm#L33

Looks like elm-test is calling `Debug.crash` when a test fails, and that's throwing up this ugly node error & stack trace.

**Comment by eeue56** [comment]
This is expected behaviour and will be staying like this until the elm-test rewrite. It's so that you get a non-zero exit number on CI, where the tests matter most.
