### ISSUE TITLE
Dot in github repository name crashes elm-test

### ISSUE THREAD

**Issue by antivanov** [elm-community/elm-test#175]
When there is a dot in the repository name elm-test crashes with a cryptic error.

```
$ elm-test
Unhandled exception while running the tests: TypeError: Cannot read property '1' of null
    at Object.repositoryToNativePackageName (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/lib/runner.js:55:12)
    at generatePackageJson (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/bin/elm-test:408:12)
    at runElmTest (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/bin/elm-test:279:22)
    at Object.<anonymous> (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/bin/elm-test:562:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

Looking into the source code or runner.js I found that the following regex is used to parse the repository name:

```js
  var matches = repository.match(/\/([^\/]+)\/([^\/\.]+)\.git/);
```

Looks like the regex should be modified and the last dot exclusion removed. Then the new regex will match all the previous package names and also the ones that include dots in them. I will create a PR.

**Comment by antivanov** [comment]
Sorry, wrong project, will create an issue for https://github.com/rtfeldman/node-test-runner instead
