### ISSUE TITLE
Weird error in synced environment

### ISSUE THREAD

**Issue by simonh1000** [elm-community/elm-test#221]
I use a sync program to keep my to dev computers in sync. It works in general, but I experience issues with elm-test, as when I switch from one computer to another, elm-test fails until I delete the elm-package directories (seemingly in both the root and `tests` directories). What I see is 

```
Unhandled exception while running the tests: { Error: EEXIST: file already exists, symlink '/Users/.../tests/elm-stuff' -> '/Users/.../elm-stuff/generated-code/elm-community/elm-test/elm-stuff'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at runElmTest (/usr/local/lib/node_modules/elm-test/lib/elm-test.js:358:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-test/lib/elm-test.js:720:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '/Users/.../tests/elm-stuff',
  dest: '/Users/.../elm-stuff/generated-code/elm-community/elm-test/elm-stuff' }
```

**Comment by drathier** [comment]
I'm 99% sure this is not an issue with elm-test. We're not touching the elm-stuff directory ourselves. Is it possible for you to exclude elm-stuff from synchronizing? It's very likely to contain per-computer data, so it should be generated locally on each device.

**Comment by simonh1000** [comment]
yes I do. I have changed the setting to avoid that and will report back when I have more data

**Comment by jnmandal** [comment]
I'm not using any kind of synced environment; just using NPM and having the same problem.

**Comment by simonh1000** [comment]
all I can add is that the frequency does seem to have gone down significantly, but I did still get the error again recently while using my other device. Had to delete all elm-stuff directories

**Comment by drathier** [comment]
Correction: the node test runner does modify elm-stuff, to add some generated elm files.

**Comment by JasonMFry** [comment]
We are also experiencing this issue, though we are using Docker which might result in a similar situation as syncing multiple computers. Removing `/project_root/elm-stuff` and `/project_root/tests/elm-stuff` did help.

**Comment by mingan** [comment]
I'm in the same boat, running elm-test@0.18.9. I have no sync running but my path setup is atypical (because of Webpacker) but I have some private packages installed using [elm-install](https://github.com/gdotdesign/elm-github-install). Not sure if it's related, I suspect the unusual path setup because before migrating to Webpacker, with normal setup (`src/` and `tests/` side by side) it worked.
