### ISSUE TITLE
Stack size exceeded with not too big data

### ISSUE THREAD

**Issue by nonpop** [elm-community/elm-test#249]
The following code causes a `RangeError: Maximum call stack size exceeded` when run on `elm-test@0.19.0-beta8` on Arch linux. This is a minimal case for my setup (cannot remove any more fields or make the lists shorter). If I change `datas 0` to `datas 3` making the tests pass, then there is no error.

```elm
module SSCCE exposing (elmTestStackExceeded)

import Expect
import Test exposing (..)


data =
    { f0 = ()
    , f1 = ()
    , f2 = ()
    , f3 = ()
    , f4 = ()
    , f5 = ()
    , f6 = ()
    , f7 = ()
    , f8 = ()
    , f9 = ()
    }


datas count =
    List.repeat count data


elmTestStackExceeded =
    test "should fail" <|
        \_ ->
            { d0 = datas 3
            , d1 = datas 3
            , d2 = datas 3
            , d3 = datas 3
            , d4 = datas 3
            , d5 = datas 3
            }
                |> Expect.equal
                    { d0 = datas 0
                    , d1 = datas 0
                    , d2 = datas 0
                    , d3 = datas 0
                    , d4 = datas 0
                    , d5 = datas 0
                    }
```

**Comment by doanythingfordethklok** [comment]
Same thing here.  I have a test that is dedupes a list. The input has 4 items and the output is checking 2 items. It appears to be the same issue as reported by OP.  Here is the full stack trace : 

```
RangeError: Maximum call stack size exceeded
    at Function.f (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:5315:11)
    at A3 (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:107:28)
    at Function.f (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:5349:4)
    at A2 (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:104:28)
    at getA (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:5636:11)
    at /some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:5241:16
    at Function.f (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:5281:5)
    at A5 (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:113:28)
    at /some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:5285:13
    at Function.f (/some-path-to-my-code/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:3923:11)
```

**Comment by ondrejsevcik** [comment]
Same issue here with `0.19.0-beta9`.

**Comment by bitterjug** [comment]
Looks like I have a similar problem with beta-10, is there a work-round?

```
elm-test 0.19.0-beta10
----------------------

...

/<project>/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:648
function _Utils_eq(x, y)
                  ^

RangeError: Maximum call stack size exceeded
    at _Utils_eq (<project>/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js:648:19)
...

There was an unexpected runtime exception while running tests
```

**Comment by nonpop** [comment]
[This](https://github.com/rtfeldman/node-test-runner/pull/319/files) fixed it for me. I don't think it's released yet but you can try it by making the changes in your node_modules/elm-test/... (Note that I accidentally posted this in the wrong repo; the 0.19 Elm package is elm-explorations/test, and the actual issue is in node-test-runner...)
